language: go

go:
  - "1.14"

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  # - go get -v github.com/rakyll/gotest

script:
  - echo "Travis File"
