steps:
  - id: 'build project'
    name: 'golang'
    args: ['go', 'build', '.']
  - id: 'deploy to production'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '1600s'
timeout: 660s
